
package it.finmatica.affarigenerali.ducd.inserisciInTitolario;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.RPC)
@WebService(name = "inserisciInTitolario", targetNamespace = "http://ducd.affarigenerali.finmatica.it/inserisciInTitolario/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InserisciInTitolario {


    /**
     * 
     * @param in
     * @return
     *     returns it.finmatica.affarigenerali.ducd.inserisciintitolario.ParametriUscita
     */
    @WebMethod(action = "http://ducd.affarigenerali.finmatica.it/inserisciInTitolario/aggiungiAFascicolo")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "aggiungiAFascicolo", targetNamespace = "http://ducd.affarigenerali.finmatica.it/inserisciInTitolario/", className = "it.finmatica.affarigenerali.ducd.inserisciintitolario.AggiungiAFascicolo")
    @ResponseWrapper(localName = "aggiungiAFascicoloResponse", targetNamespace = "http://ducd.affarigenerali.finmatica.it/inserisciInTitolario/", className = "it.finmatica.affarigenerali.ducd.inserisciintitolario.AggiungiAFascicoloResponse")
    public ParametriUscita aggiungiAFascicolo(
        @WebParam(name = "in", targetNamespace = "")
            ParametriIngresso in);

    /**
     * 
     * @param in
     * @return
     *     returns it.finmatica.affarigenerali.ducd.inserisciintitolario.ParametriUscita
     */
    @WebMethod(action = "http://ducd.affarigenerali.finmatica.it/inserisciInTitolario/creaFascicolo")
    @WebResult(name = "out", targetNamespace = "")
    @RequestWrapper(localName = "creaFascicolo", targetNamespace = "http://ducd.affarigenerali.finmatica.it/inserisciInTitolario/", className = "it.finmatica.affarigenerali.ducd.inserisciintitolario.CreaFascicolo")
    @ResponseWrapper(localName = "creaFascicoloResponse", targetNamespace = "http://ducd.affarigenerali.finmatica.it/inserisciInTitolario/", className = "it.finmatica.affarigenerali.ducd.inserisciintitolario.CreaFascicoloResponse")
    public ParametriUscita creaFascicolo(
        @WebParam(name = "in", targetNamespace = "")
            ParametriIngresso in);

}
