
package it.finmatica.protocollo.integrazioni.protocolloextended;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProtocolloExtendedServiceService", targetNamespace = "http://protocolloextended.finmatica.it/", wsdlLocation = "http://test-agspr-as:8888/agspr/services/ProtocolloExtendedServicePort?wsdl")
public class ProtocolloExtendedServiceService
    extends Service
{

    private final static URL PROTOCOLLOEXTENDEDSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException PROTOCOLLOEXTENDEDSERVICESERVICE_EXCEPTION;
    private final static QName PROTOCOLLOEXTENDEDSERVICESERVICE_QNAME = new QName("http://protocolloextended.finmatica.it/", "ProtocolloExtendedServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://test-agspr-as:8888/agspr/services/ProtocolloExtendedServicePort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROTOCOLLOEXTENDEDSERVICESERVICE_WSDL_LOCATION = url;
        PROTOCOLLOEXTENDEDSERVICESERVICE_EXCEPTION = e;
    }

    public ProtocolloExtendedServiceService() {
        super(__getWsdlLocation(), PROTOCOLLOEXTENDEDSERVICESERVICE_QNAME);
    }

    public ProtocolloExtendedServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROTOCOLLOEXTENDEDSERVICESERVICE_QNAME, features);
    }

    public ProtocolloExtendedServiceService(URL wsdlLocation) {
        super(wsdlLocation, PROTOCOLLOEXTENDEDSERVICESERVICE_QNAME);
    }

    public ProtocolloExtendedServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROTOCOLLOEXTENDEDSERVICESERVICE_QNAME, features);
    }

    public ProtocolloExtendedServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProtocolloExtendedServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProtocolloExtendedService
     */
    @WebEndpoint(name = "ProtocolloExtendedServicePort")
    public ProtocolloExtendedService getProtocolloExtendedServicePort() {
        return super.getPort(new QName("http://protocolloextended.finmatica.it/", "ProtocolloExtendedServicePort"), ProtocolloExtendedService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProtocolloExtendedService
     */
    @WebEndpoint(name = "ProtocolloExtendedServicePort")
    public ProtocolloExtendedService getProtocolloExtendedServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://protocolloextended.finmatica.it/", "ProtocolloExtendedServicePort"), ProtocolloExtendedService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROTOCOLLOEXTENDEDSERVICESERVICE_EXCEPTION!= null) {
            throw PROTOCOLLOEXTENDEDSERVICESERVICE_EXCEPTION;
        }
        return PROTOCOLLOEXTENDEDSERVICESERVICE_WSDL_LOCATION;
    }

}
