
package it.finmatica.protocollo.integrazioni.protocolloextended;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.RPC)
@WebService(targetNamespace = "http://protocolloextended.finmatica.it/", name = "DOCAREAProtoExtended",portName = "ProtocolloExtendedServicePort")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProtocolloExtendedService {


    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getDocumentiProtocollati")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentiProtocollati", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetDocumentiProtocollati")
    @ResponseWrapper(localName = "getDocumentiProtocollatiResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetDocumentiProtocollatiResponse")
    public String getDocumentiProtocollati(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "modFascicolo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modFascicolo", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.ModFascicolo")
    @ResponseWrapper(localName = "modFascicoloResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.ModFascicoloResponse")
    public String modFascicolo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:GetFascicoli")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFascicoli", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetFascicoli")
    @ResponseWrapper(localName = "getFascicoliResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetFascicoliResponse")
    public String getFascicoli(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "modProtocollo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modProtocollo", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.ModProtocollo")
    @ResponseWrapper(localName = "modProtocolloResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.ModProtocolloResponse")
    public String modProtocollo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "collegaFascicoli")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "collegaFascicoli", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.CollegaFascicoli")
    @ResponseWrapper(localName = "collegaFascicoliResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.CollegaFascicoliResponse")
    public String collegaFascicoli(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getInfoPec")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInfoPec", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetInfoPec")
    @ResponseWrapper(localName = "getInfoPecResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetInfoPecResponse")
    public String getInfoPec(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "addFilePrincipale")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addFilePrincipale", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.AddFilePrincipale")
    @ResponseWrapper(localName = "addFilePrincipaleResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.AddFilePrincipaleResponse")
    public String addFilePrincipale(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "delFilePrincipale")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delFilePrincipale", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.DelFilePrincipale")
    @ResponseWrapper(localName = "delFilePrincipaleResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.DelFilePrincipaleResponse")
    public String delFilePrincipale(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "delDocumento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delDocumento", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.DelDocumento")
    @ResponseWrapper(localName = "delDocumentoResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.DelDocumentoResponse")
    public String delDocumento(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getClassifiche")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClassifiche", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetClassifiche")
    @ResponseWrapper(localName = "getClassificheResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetClassificheResponse")
    public String getClassifiche(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "addRapporto")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addRapporto", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.AddRapporto")
    @ResponseWrapper(localName = "addRapportoResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.AddRapportoResponse")
    public String addRapporto(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getDocumentiNonProtocollati")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentiNonProtocollati", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetDocumentiNonProtocollati")
    @ResponseWrapper(localName = "getDocumentiNonProtocollatiResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetDocumentiNonProtocollatiResponse")
    public String getDocumentiNonProtocollati(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "collegaDocumenti")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "collegaDocumenti", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.CollegaDocumenti")
    @ResponseWrapper(localName = "collegaDocumentiResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.CollegaDocumentiResponse")
    public String collegaDocumenti(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "creaFascicolo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "creaFascicolo", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.CreaFascicolo")
    @ResponseWrapper(localName = "creaFascicoloResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.CreaFascicoloResponse")
    public String creaFascicolo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "rimuoviDocumentoDalFascicolo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rimuoviDocumentoDalFascicolo", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.RimuoviDocumentoDalFascicolo")
    @ResponseWrapper(localName = "rimuoviDocumentoDalFascicoloResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.RimuoviDocumentoDalFascicoloResponse")
    public String rimuoviDocumentoDalFascicolo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "inserisciDocumentoInFascicolo",operationName = "inserisciDocumentoInFascicolo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inserisciDocumentoInFascicolo", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.InserisciDocumentoInFascicolo")
    @ResponseWrapper(localName = "inserisciDocumentoInFascicoloResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.InserisciDocumentoInFascicoloResponse")
    public String inserisciDocumentoInFascicolo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     *
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "inserisciDocumentoInFascicoloSecondario",operationName = "inserisciDocumentoInFascicoloSecondario")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "inserisciDocumentoInFascicoloSecondario", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.InserisciDocumentoInFascicolo")
    @ResponseWrapper(localName = "inserisciDocumentoInFascicoloSecondarioResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.InserisciDocumentoInFascicoloResponse")
    String inserisciDocumentoInFascicoloSecondario(
        @WebParam(name = "user", targetNamespace = "")
            String user,
        @WebParam(name = "DST", targetNamespace = "")
            String dst,
        @WebParam(name = "xml", targetNamespace = "")
            String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getDocumento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumento", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetDocumento")
    @ResponseWrapper(localName = "getDocumentoResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetDocumentoResponse")
    public String getDocumento(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "creaDocumento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "creaDocumento", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.CreaDocumento")
    @ResponseWrapper(localName = "creaDocumentoResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.CreaDocumentoResponse")
    public String creaDocumento(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "delFascicolo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delFascicolo", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.DelFascicolo")
    @ResponseWrapper(localName = "delFascicoloResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.DelFascicoloResponse")
    public String delFascicolo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "modDocumento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modDocumento", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.ModDocumento")
    @ResponseWrapper(localName = "modDocumentoResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.ModDocumentoResponse")
    public String modDocumento(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "delSmistamento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delRapporto", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.DelRapporto")
    @ResponseWrapper(localName = "delRapportoResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.DelRapportoResponse")
    public String delRapporto(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "addSmistamento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addSmistamento", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.AddSmistamento")
    @ResponseWrapper(localName = "addSmistamentoResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.AddSmistamentoResponse")
    public String addSmistamento(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     * 
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "delSmistamento")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delSmistamento", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.DelSmistamento")
    @ResponseWrapper(localName = "delSmistamentoResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.DelSmistamentoResponse")
    public String delSmistamento(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "DST", targetNamespace = "")
        String dst,
        @WebParam(name = "xml", targetNamespace = "")
        String xml);

    /**
     *
     * @param dst
     * @param xml
     * @param user
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "getUrlBarcodeProtocollo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUrlBarcodeProtocollo", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetUrlBarcodeProtocollo")
    @ResponseWrapper(localName = "getUrlBarcodeProtocolloResponse", targetNamespace = "http://protocolloextended.finmatica.it/", className = "it.finmatica.protocolloextended.GetUrlBarcodeProtocolloResponse")
    public String getUrlBarcodeProtocollo(
        @WebParam(name = "user", targetNamespace = "")
            String user,
        @WebParam(name = "DST", targetNamespace = "")
            String dst,
        @WebParam(name = "xml", targetNamespace = "")
            String xml);

}
