--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_92.ins_istruzioni.sql  failOnError:false
Insert into DBFW_ISTRUZIONI
   (NOME, MODULO, TIPO, VALIDA,
    UTENTE_INSERIMENTO, DATA_INSERIMENTO, UTENTE_AGGIORNAMENTO, DATA_AGGIORNAMENTO, DI_SISTEMA,
    BLOCKSIZE, NAVIGATION, TEXT_SQL, TIPO_CONNESSIONE)
 Values
   ('AG_GET_ID_TIPO_PROTOCOLLO_DEFAULT', 'AGSPR', 'SELECT', 'S',
    'DBFW', sysdate, 'DBFW', sysdate, 'N',
    50, 'next', 'select AGSPR_AGP_TRASCO_PKG.GET_ID_TIPO_PROTOCOLLO_DEFAULT(''PEC'') ID_TIPO_PROTOCOLLO_DEFAULT from dual ', 'AD4')
/

Insert into DBFW_ISTRUZIONI
   (NOME, MODULO, TIPO, DESCRIZIONE,
    VALIDA, UTENTE_INSERIMENTO, DATA_INSERIMENTO, UTENTE_AGGIORNAMENTO, DATA_AGGIORNAMENTO,
    DI_SISTEMA, MODALITA, BLOCKSIZE, NAVIGATION, TEXT_SQL,
    TIPO_RITORNO, TIPO_CONNESSIONE)
 Values
   ('AG_DOCUMENTO_UTILITY_CREA_PROTOCOLLO_AGSPR', 'AGSPR', 'FUNCTION', 'AG_DOCUMENTO_UTILITY_CREA_PROTOCOLLO_AGSPR',
    'S', 'WIZARD', TO_DATE('11/12/2018 17:37:41', 'MM/DD/YYYY HH24:MI:SS'), 'WIZARD', TO_DATE('11/12/2018 17:37:41', 'MM/DD/YYYY HH24:MI:SS'),
    'N', 'execute', 50, 'next', 'AG_DOCUMENTO_UTILITY.CREA_PROTOCOLLO_AGSPR',
    'VARCHAR2', 'AD4')
/

Insert into DBFW_ISTRUZIONI_PARAMETRI
   (NOME_ISTRUZIONE, NOME, SEQUENZA, DIRECTION)
 Values
   ('AG_DOCUMENTO_UTILITY_CREA_PROTOCOLLO_AGSPR', 'P_ID_DOCUMENTO', 0, 'IN')
/

Insert into DBFW_ISTRUZIONI_PARAMETRI
   (NOME_ISTRUZIONE, NOME, SEQUENZA, DIRECTION)
 Values
   ('AG_DOCUMENTO_UTILITY_CREA_PROTOCOLLO_AGSPR', 'P_UTENTE', 1, 'IN')
/

Insert into DBFW_ISTRUZIONI_PARAMETRI
   (NOME_ISTRUZIONE, NOME, SEQUENZA, DIRECTION)
 Values
   ('AG_DOCUMENTO_UTILITY_CREA_PROTOCOLLO_AGSPR', 'P_ID_TIPO_PROTOCOLLO', 2, 'IN')
/
