
package it.finmatica.affarigenerali.ducd.entiAooUtility;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EntiAooUtilitySoapBindingImplService", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", wsdlLocation = "http://test-agspr-as/ducd/services/EntiAooUtilitySoapBindingImpl?wsdl")
public class EntiAooUtilitySoapBindingImplService
    extends Service
{

    private final static URL ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_EXCEPTION;
    private final static QName ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_QNAME = new QName("http://protocolloUtility.ducd.affarigenerali.finmatica.it", "EntiAooUtilitySoapBindingImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://test-agspr-as/ducd/services/EntiAooUtilitySoapBindingImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_WSDL_LOCATION = url;
        ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_EXCEPTION = e;
    }

    public EntiAooUtilitySoapBindingImplService() {
        super(__getWsdlLocation(), ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_QNAME);
    }

    public EntiAooUtilitySoapBindingImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_QNAME, features);
    }

    public EntiAooUtilitySoapBindingImplService(URL wsdlLocation) {
        super(wsdlLocation, ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_QNAME);
    }

    public EntiAooUtilitySoapBindingImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_QNAME, features);
    }

    public EntiAooUtilitySoapBindingImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EntiAooUtilitySoapBindingImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EntiAooUtilitySoapBindingImpl
     */
    @WebEndpoint(name = "EntiAooUtilitySoapBindingImpl")
    public EntiAooUtilitySoapBindingImpl getEntiAooUtilitySoapBindingImpl() {
        return super.getPort(new QName("http://protocolloUtility.ducd.affarigenerali.finmatica.it", "EntiAooUtilitySoapBindingImpl"), EntiAooUtilitySoapBindingImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EntiAooUtilitySoapBindingImpl
     */
    @WebEndpoint(name = "EntiAooUtilitySoapBindingImpl")
    public EntiAooUtilitySoapBindingImpl getEntiAooUtilitySoapBindingImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://protocolloUtility.ducd.affarigenerali.finmatica.it", "EntiAooUtilitySoapBindingImpl"), EntiAooUtilitySoapBindingImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_EXCEPTION!= null) {
            throw ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_EXCEPTION;
        }
        return ENTIAOOUTILITYSOAPBINDINGIMPLSERVICE_WSDL_LOCATION;
    }

}
