
package it.finmatica.affarigenerali.ducd.entiAooUtility;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.RPC) //TODO VERIFICARE
@WebService(name = "EntiAooUtilitySoapBindingImpl", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntiAooUtilitySoapBindingImpl {


    /**
     * 
     * @param dataInput
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(name = "checkDateReturn", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
    @RequestWrapper(localName = "checkDate", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolloutility.CheckDate")
    @ResponseWrapper(localName = "checkDateResponse", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolloutility.CheckDateResponse")
    public boolean checkDate(
        @WebParam(name = "data_input", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            String dataInput);

    /**
     * 
     * @param indirizzoMail
     * @param descrizioneAmministrazione
     * @param codiceAoo
     * @param codiceAmministrazione
     * @param descrizioneAoo
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getMailEnteReturn", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
    @RequestWrapper(localName = "getMailEnte", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolloutility.GetMailEnte")
    @ResponseWrapper(localName = "getMailEnteResponse", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolloutility.GetMailEnteResponse")
    public String getMailEnte(
        @WebParam(name = "codice_amministrazione", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            String codiceAmministrazione,
        @WebParam(name = "descrizione_amministrazione", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            String descrizioneAmministrazione,
        @WebParam(name = "codice_aoo", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            String codiceAoo,
        @WebParam(name = "descrizione_aoo", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            String descrizioneAoo,
        @WebParam(name = "indirizzo_mail", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            String indirizzoMail);

    /**
     * 
     * @param inputXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getProtocolliDaRicevereReturn", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
    @RequestWrapper(localName = "getProtocolliDaRicevere", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolloutility.GetProtocolliDaRicevere")
    @ResponseWrapper(localName = "getProtocolliDaRicevereResponse", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolloutility.GetProtocolliDaRicevereResponse")
    public String getProtocolliDaRicevere(
        @WebParam(name = "inputXml", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            String inputXml);

    /**
     * 
     * @param inputXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getProtocolliReturn", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
    @RequestWrapper(localName = "getProtocolli", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolloutility.GetProtocolli")
    @ResponseWrapper(localName = "getProtocolliResponse", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolloutility.GetProtocolliResponse")
    public String getProtocolli(
        @WebParam(name = "inputXml", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            String inputXml);

    /**
     * 
     * @param anno
     * @param numero
     * @param tipoRegistro
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "getProtocolloReturn", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
    @RequestWrapper(localName = "getProtocollo", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolloutility.GetProtocollo")
    @ResponseWrapper(localName = "getProtocolloResponse", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolloutility.GetProtocolloResponse")
    public String getProtocollo(
        @WebParam(name = "anno", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            int anno,
        @WebParam(name = "numero", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            int numero,
        @WebParam(name = "tipoRegistro", targetNamespace = "http://protocolloUtility.ducd.affarigenerali.finmatica.it")
            String tipoRegistro);

}
