--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_006.agp_protocolli_alter failOnError:false
alter table AGP_DOCUMENTI_DATI_SCARTO RENAME COLUMN ID_DOCUMENTO TO ID_DOCUMENTO_DATI_SCARTO
/

ALTER TABLE AGP_PROTOCOLLI
 ADD CONSTRAINT AGP_PROT_DDSC_FK
  FOREIGN KEY (ID_PROTOCOLLO_DATI_SCARTO)
  REFERENCES AGP_DOCUMENTI_DATI_SCARTO (ID_DOCUMENTO_DATI_SCARTO)
/

create unique index AGP_PROT_DDSC_FK on AGP_PROTOCOLLI (ID_PROTOCOLLO_DATI_SCARTO)
/

DROP INDEX AGP_PROT_PDIN_FK
/

CREATE UNIQUE INDEX AGP_PROT_PDIN_FK ON AGP_PROTOCOLLI
(ID_PROTOCOLLO_DATI_INTEROP)
/