--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_007.agp_protocolli_dati_reg_giorn
CREATE TABLE AGP_PROTOCOLLI_DATI_REG_GIORN
(
   ID_PROTOCOLLO_DATI_REG_GIORN    NUMBER NOT NULL,
   PRIMO_NUMERO                    NUMBER,
   DATA_PRIMO_NUMERO               DATE,
   ULTIMO_NUMERO                   NUMBER,
   DATA_ULTIMO_NUMERO              DATE,
   TOTALE_PROTOCOLLI               NUMBER NOT NULL,
   TOTALE_ANNULLATI                NUMBER NOT NULL,
   RICERCA_DATA_DAL                DATE NOT NULL,
   RICERCA_DATA_AL                 DATE NOT NULL
)
/

ALTER TABLE AGP_PROTOCOLLI_DATI_REG_GIORN ADD (
  CONSTRAINT AGP_PROT_DATI_REG_GIORN_PK
  PRIMARY KEY
  (ID_PROTOCOLLO_DATI_REG_GIORN)
  ENABLE VALIDATE)
/

ALTER TABLE AGP_PROTOCOLLI
ADD (ID_PROTOCOLLO_DATI_REG_GIORN NUMBER)
/

ALTER TABLE AGP_PROTOCOLLI ADD (
  CONSTRAINT AGP_PROT_PDRG_FK
  FOREIGN KEY (ID_PROTOCOLLO_DATI_REG_GIORN)
  REFERENCES AGP_PROTOCOLLI_DATI_REG_GIORN (ID_PROTOCOLLO_DATI_REG_GIORN)
  ENABLE VALIDATE)
/

CREATE UNIQUE INDEX AGP_PROT_PDRG_FK
   ON AGP_PROTOCOLLI (ID_PROTOCOLLO_DATI_REG_GIORN)
/