--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_008.agp_protocolli_dati_emergenza
CREATE TABLE AGP_PROTOCOLLI_DATI_EMERGENZA
(
   ID_PROTOCOLLO_DATI_EMERGENZA   NUMBER NOT NULL,
   MOTIVO_EMERGENZA               VARCHAR2 (255),
   PROVVEDIMENTO_EMERGENZA        VARCHAR2 (255),
   DATA_INIZIO_EMERGENZA          DATE,
   DATA_FINE_EMERGENZA            DATE,
   VERSION                        NUMBER,
   UTENTE_INS                     VARCHAR2(255),
   DATA_INS                       DATE,
   UTENTE_UPD                     VARCHAR2(255),
   DATA_UPD                       DATE
)
/

ALTER TABLE AGP_PROTOCOLLI_DATI_EMERGENZA ADD (
  CONSTRAINT AGP_PROTOCOLLI_DATI_EMERG_PK
  PRIMARY KEY
  (ID_PROTOCOLLO_DATI_EMERGENZA)
  ENABLE VALIDATE)
/

ALTER TABLE AGP_PROTOCOLLI
add (ID_PROTOCOLLO_DATI_EMERGENZA number,
  ANNO_EMERGENZA                NUMBER,
  NUMERO_EMERGENZA              NUMBER,
  REGISTRO_EMERGENZA            VARCHAR2(255))
/

ALTER TABLE AGP_PROTOCOLLI ADD (
  CONSTRAINT AGP_PROT_PDEM_FK 
  FOREIGN KEY (ID_PROTOCOLLO_DATI_EMERGENZA) 
  REFERENCES AGP_PROTOCOLLI_DATI_EMERGENZA (ID_PROTOCOLLO_DATI_EMERGENZA)
  ENABLE VALIDATE)
/

create unique index AGP_PROT_PDEM_FK on AGP_PROTOCOLLI (ID_PROTOCOLLO_DATI_EMERGENZA)
/