--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_010.agp_schemi_prot_categorie
CREATE TABLE AGP_SCHEMI_PROT_CATEGORIE
(
   ID_SCHEMA_PROT_CATEGORIA   NUMBER NOT NULL,
   ID_SCHEMA_PROTOCOLLO       NUMBER NOT NULL,
   CATEGORIA                  VARCHAR2 (255) NOT NULL,
   ID_TIPO_PROTOCOLLO         NUMBER,
   VERSION                    NUMBER,
   VALIDO                     CHAR (1) DEFAULT 'Y' NOT NULL,
   UTENTE_INS                 VARCHAR2 (20),
   DATA_INS                   DATE,
   UTENTE_UPD                 VARCHAR2 (20),
   DATA_UPD                   DATE
)
/

CREATE UNIQUE INDEX AGP_SCHEMI_PROT_CATEGORIE_PK
   ON AGP_SCHEMI_PROT_CATEGORIE (ID_SCHEMA_PROT_CATEGORIA)
/

ALTER TABLE AGP_SCHEMI_PROT_CATEGORIE ADD (
  CONSTRAINT AGP_SCHEMI_PROT_CATEGORIE_PK
  PRIMARY KEY
  (ID_SCHEMA_PROT_CATEGORIA)
  ENABLE VALIDATE)
/

CREATE INDEX AGP_SPCA_TIPR_FK
   ON AGP_SCHEMI_PROT_CATEGORIE (ID_TIPO_PROTOCOLLO)
/

ALTER TABLE AGP_SCHEMI_PROT_CATEGORIE ADD (
  CONSTRAINT AGP_SPCA_TIPR_FK
  FOREIGN KEY (ID_TIPO_PROTOCOLLO)
  REFERENCES AGP_TIPI_PROTOCOLLO (ID_TIPO_PROTOCOLLO)
  ENABLE VALIDATE)
/

ALTER TABLE AGP_SCHEMI_PROT_CATEGORIE ADD (
  CONSTRAINT AGP_SPCA_CATEGORIA_CC
  CHECK (CATEGORIA IN ('LETTERA','PROTOCOLLO','PEC','EMERGENZA','PROVVEDIMENTO','REGISTRO_GIORNALIERO','DA_NON_PROTOCOLLARE', 'TUTTE'))
  ENABLE VALIDATE)
/

CREATE UNIQUE INDEX AGP_SCHEMI_PROT_CATEGORIE_UK
   ON AGP_SCHEMI_PROT_CATEGORIE (ID_SCHEMA_PROTOCOLLO,
                                 CATEGORIA,
                                 ID_TIPO_PROTOCOLLO)
/