--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_034.agp_protocolli_rif_telematici
CREATE TABLE AGP_PROTOCOLLI_RIF_TELEMATICI
(
  ID_PROTOCOLLO_RIF_TELEMATICO  NUMBER            NOT NULL,
  ID_DOCUMENTO                  NUMBER            NOT NULL,
  URI                           VARCHAR2(255)     NOT NULL,
  DIMENSIONE                    NUMBER,
  IMPRONTA                      VARCHAR2(4000),
  IMPRONTA_ALGORITMO            VARCHAR2(255),
  IMPRONTA_CODIFICA             VARCHAR2(255),
  TIPO                          VARCHAR2(255),
  CORRETTEZZA_IMPRONTA          VARCHAR2(1),
  SCARICATO                     CHAR(1)      DEFAULT 'N',
  VALIDO                        CHAR(1)      DEFAULT 'Y',
  UTENTE_INS                    VARCHAR2(255),
  DATA_INS                      DATE,
  UTENTE_UPD                    VARCHAR2(255),
  DATA_UPD                      DATE,
  VERSION                       NUMBER            NOT NULL
)
/


CREATE INDEX AGP_PRTE_PROT_FK ON AGP_PROTOCOLLI_RIF_TELEMATICI
(ID_DOCUMENTO)
/



ALTER TABLE AGP_PROTOCOLLI_RIF_TELEMATICI ADD (
  CONSTRAINT AGP_PROTOCOLLI_RIF_TELEM_PK
  PRIMARY KEY
  (ID_PROTOCOLLO_RIF_TELEMATICO)
  ENABLE VALIDATE)
/


ALTER TABLE AGP_PROTOCOLLI_RIF_TELEMATICI ADD (
  CONSTRAINT AGP_PRTE_PROT_FK
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES AGP_PROTOCOLLI (ID_DOCUMENTO)
  ENABLE VALIDATE)
/