--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_035.job_scheduler
CREATE TABLE JOB_CONFIG
(
   ID_JOB_CONFIG         NUMBER (19) NOT NULL,
   CRON                  VARCHAR2 (255 CHAR),
   ESCLUSIVO             CHAR (1 CHAR) NOT NULL,
   NOME_BEAN             VARCHAR2 (255 CHAR),
   PARAMETRI             VARCHAR2 (255 CHAR),
   PROSSIMA_ESECUZIONE   TIMESTAMP (6),
   STATO                 VARCHAR2 (255 CHAR),
   TITOLO                VARCHAR2 (255 CHAR),
   VALIDO                CHAR (1 CHAR) NOT NULL,
   VERSION               NUMBER (19) NOT NULL
)
/

CREATE UNIQUE INDEX JOB_CONFIG_PK
   ON JOB_CONFIG (ID_JOB_CONFIG)
/

ALTER TABLE JOB_CONFIG ADD (
CONSTRAINT JOB_CONFIG_PK
  PRIMARY KEY
  (ID_JOB_CONFIG)
  ENABLE VALIDATE)
/
CREATE TABLE JOB_LOG
(
   ID_JOB_LOG      NUMBER (19) NOT NULL,
   DATA_FINE       TIMESTAMP (6),
   DATA_INIZIO     TIMESTAMP (6),
   NODO            VARCHAR2 (255),
   NOTE            VARCHAR2 (255),
   STACKTRACE      VARCHAR2 (255),
   STATO           VARCHAR2 (255),
   ID_JOB_CONFIG   NUMBER (19),
   VERSION         NUMBER (19) NOT NULL
)
/
CREATE UNIQUE INDEX JOB_LOG_PK
   ON JOB_LOG (ID_JOB_LOG)
/
ALTER TABLE JOB_LOG ADD (
CONSTRAINT JOB_LOG_PK
  PRIMARY KEY
  (ID_JOB_LOG)
  ENABLE VALIDATE)
/

ALTER TABLE JOB_LOG ADD (
  CONSTRAINT JOB_LOG_CONF_FK
  FOREIGN KEY (ID_JOB_CONFIG)
  REFERENCES JOB_CONFIG (ID_JOB_CONFIG))
/

CREATE INDEX JOB_LOG_CONF_FK
   ON JOB_LOG (ID_JOB_CONFIG)
/