--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_049.agp_msg_inviati_dati_prot
CREATE TABLE AGP_MSG_INVIATI_DATI_PROT
(
   ID_DOCUMENTO             NUMBER NOT NULL,
   ID_MESSAGGIO_SI4CS       NUMBER NOT NULL,
   OGGETTO                  VARCHAR2 (2000),
   CORPO                    CLOB,
   DATA_SPEDIZIONE          DATE,
   MITTENTE                 VARCHAR2 (2000),
   DESTINATARI              CLOB,
   DESTINATARI_CONOSCENZA   CLOB,
   DESTINATARI_NASCOSTI     CLOB,
   TAGMAIL                  VARCHAR2 (255),
   SPEDITO                  VARCHAR2 (255),
   ACCETTAZIONE             CHAR (1) DEFAULT 'N' NOT NULL,
   NON_ACCETTAZIONE         CHAR (1) DEFAULT 'N' NOT NULL
)
/


CREATE INDEX AGP_MIDA_DOCU_FK
   ON AGP_MSG_INVIATI_DATI_PROT (ID_DOCUMENTO)
/



ALTER TABLE AGP_MSG_INVIATI_DATI_PROT ADD (
  CONSTRAINT AGP_MSG_INVIATI_DATI_PROT_PK
  PRIMARY KEY
  (ID_DOCUMENTO)
  ENABLE VALIDATE)
/

ALTER TABLE AGP_MSG_INVIATI_DATI_PROT ADD (
  CONSTRAINT AGP_MSG_INVIATI_DATI_PROT_UK
  UNIQUE (ID_MESSAGGIO_SI4CS)
  ENABLE VALIDATE)
/


ALTER TABLE AGP_MSG_INVIATI_DATI_PROT ADD (
  CONSTRAINT AGP_MIDA_DOCU_FK
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES GDO_DOCUMENTI (ID_DOCUMENTO)
  ENABLE VALIDATE)
/