--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_052.agp_msg_ricevuti_dati_prot
CREATE TABLE AGP_MSG_RICEVUTI_DATI_PROT
(
   ID_DOCUMENTO             NUMBER NOT NULL,
   ID_MESSAGGIO_SI4CS       NUMBER NOT NULL,
   OGGETTO                  VARCHAR2 (2000),
   TESTO                    CLOB,
   MIME_TESTO               VARCHAR2 (255),
   DATA_RICEZIONE           DATE,
   MITTENTE                 VARCHAR2 (2000),
   DESTINATARI              CLOB,
   DESTINATARI_CONOSCENZA   CLOB,
   DESTINATARI_NASCOSTI     CLOB,
   TIPO                     VARCHAR2 (255),
   STATO                    VARCHAR2 (255) DEFAULT 'DA_GESTIRE' NOT NULL,
   DATA_STATO               DATE DEFAULT SYSDATE NOT NULL,
   ID_CLASSIFICAZIONE       NUMBER,
   ID_FASCICOLO             NUMBER,
   NOTE                     VARCHAR2 (4000)
)
/



CREATE INDEX AGP_MRDA_DOCU_FK
   ON AGP_MSG_RICEVUTI_DATI_PROT (ID_DOCUMENTO)
/

ALTER TABLE AGP_MSG_RICEVUTI_DATI_PROT ADD (
  CONSTRAINT AGP_MSG_RIC_DATI_PROT_STATO_CC
  CHECK (STATO IN ('DA_GESTIRE', 'DA_PROTOCOLLARE_CON_SEGNATURA', 'DA_PROTOCOLLARE_SENZA_SEGNATURA', 'GESTITO', 'GENERATA_ECCEZIONE', 'NON_PROTOCOLLATO', 'PROTOCOLLATO', 'SCARTATO') AND STATO = UPPER(STATO))
  ENABLE VALIDATE)
/

ALTER TABLE AGP_MSG_RICEVUTI_DATI_PROT ADD (
  CONSTRAINT AGP_MSG_RICEVUTI_DATI_PROT_PK
  PRIMARY KEY
  (ID_DOCUMENTO)
  ENABLE VALIDATE)
/

ALTER TABLE AGP_MSG_RICEVUTI_DATI_PROT ADD (
  CONSTRAINT AGP_MESSAGGI_DATI_PROT_UK
  UNIQUE (ID_MESSAGGIO_SI4CS)
  ENABLE VALIDATE)
/


ALTER TABLE AGP_MSG_RICEVUTI_DATI_PROT ADD (
  CONSTRAINT AGP_MRDA_DOCU_FK
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES GDO_DOCUMENTI (ID_DOCUMENTO)
  ENABLE VALIDATE)
/