--liquibase formatted sql
--changeset mfrancesconi:4.0.0.0_20200226_127_1_ins_agp_documenti_dati_scarto_log

INSERT INTO AGP_DOCUMENTI_DATI_SCARTO_LOG (
   ID_DOCUMENTO_DATI_SCARTO, REV, REVTYPE, 
   REVEND, STATO, STATO_MOD, 
   DATA_STATO, DATA_STATO_MOD, NULLA_OSTA, 
   NULLA_OSTA_MOD, DATA_NULLA_OSTA, DATA_NULLA_OSTA_MOD, 
   UTENTE_INS, UTENTE_INS_MOD, DATA_INS, 
   DATE_CREATED_MOD, UTENTE_UPD, UTENTE_UPD_MOD, 
   DATA_UPD, LAST_UPDATED_MOD) 
SELECT 
ID_PROTOCOLLO_DATI_SCARTO, REV, REVTYPE, 
   REVEND, STATO, STATO_MOD, 
   DATA_STATO, DATA_STATO_MOD, NULLA_OSTA, 
   NULLA_OSTA_MOD, DATA_NULLA_OSTA, DATA_NULLA_OSTA_MOD, 
   UTENTE_INS, UTENTE_INS_MOD, DATA_INS, 
   DATE_CREATED_MOD, UTENTE_UPD, UTENTE_UPD_MOD, 
   DATA_UPD, LAST_UPDATED_MOD
FROM AGP_PROTOCOLLI_DATI_SCARTO_LOG
/