--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_129.agp_protocolli_dati_scarto
CREATE OR REPLACE FORCE VIEW AGP_PROTOCOLLI_DATI_SCARTO
(ID_PROTOCOLLO_DATI_SCARTO, STATO, DATA_STATO, NULLA_OSTA, DATA_NULLA_OSTA, 
 UTENTE_INS, DATA_INS, UTENTE_UPD, DATA_UPD, VERSION)
AS 
SELECT 
ID_DOCUMENTO_DATI_SCARTO ID_PROTOCOLLO_DATI_SCARTO, STATO, DATA_STATO, 
   NULLA_OSTA, DATA_NULLA_OSTA, UTENTE_INS, 
   DATA_INS, UTENTE_UPD, DATA_UPD, 
   VERSION
FROM AGP_DOCUMENTI_DATI_SCARTO
/