--liquibase formatted sql
--changeset mmalferrari:4.0.0.0_20200313_159_temp_table_create

CREATE GLOBAL TEMPORARY TABLE TEMP_STORICO
(
  ID_DOCUMENTO           NUMBER,
  REV                    NUMBER,
  ID_DOCUMENTO_PROT_GDM  NUMBER,
  LOG_DATA               DATE,
  LOG_UTENTE             VARCHAR2(20),
  TABELLA                VARCHAR2(4000)
)
ON COMMIT DELETE ROWS
/
CREATE GLOBAL TEMPORARY TABLE TEMP_STORICO_ALLE
(
  ID                        NUMBER,
  ID_DOCUMENTO              NUMBER,
  IDRIF                     VARCHAR2(20),
  LOG_ID_DOCUMENTO          NUMBER,
  LOG_DATA                  DATE,
  LOG_UTENTE                VARCHAR2(20),
  ID_VALORE_LOG             NUMBER,
  DESCRIZIONE               VARCHAR2(4000),
  TITOLO_DOCUMENTO          VARCHAR2(4000),
  QUANTITA                  NUMBER,
  NUMERO_PAG                NUMBER,
  RISERVATO                 VARCHAR2(4000),
  UBICAZIONE_DOC_ORIGINALE  VARCHAR2(4000),
  DESCRIZIONE_MOD           NUMBER,
  TITOLO_DOCUMENTO_MOD      NUMBER,
  QUANTITA_MOD              NUMBER,
  NUMERO_PAG_MOD            NUMBER,
  RISERVATO_MOD             NUMBER,
  CONOSCENZA_MOD            NUMBER,
  UBICAZIONE_DOC_ORIG_MOD   NUMBER
)
ON COMMIT DELETE ROWS
/
drop table TEMP_STORICO_CORR
/
CREATE GLOBAL TEMPORARY TABLE TEMP_STORICO_CORR
(
  ID                           NUMBER           NOT NULL,
  ID_DOCUMENTO                 NUMBER           NOT NULL,
  IDRIF                        VARCHAR2(20),
  LOG_ID_DOCUMENTO             NUMBER           NOT NULL,
  LOG_DATA                     DATE,
  LOG_UTENTE                   VARCHAR2(20),
  ID_VALORE_LOG                NUMBER,
  DENOMINAZIONE_PER_SEGNATURA  VARCHAR2(4000),
  COGNOME_PER_SEGNATURA        VARCHAR2(4000),
  NOME_PER_SEGNATURA           VARCHAR2(4000),
  DESCRIZIONE_AMM              VARCHAR2(4000),
  DESCRIZIONE_AOO              VARCHAR2(4000),
  CONOSCENZA                   VARCHAR2(4000),
  DENOMINAZIONE_MOD            NUMBER,
  COGNOME_MOD                  NUMBER,
  NOME_MOD                     NUMBER,
  DESCRIZIONE_AMM_MOD          NUMBER,
  DESCRIZIONE_AOO_MOD          NUMBER,
  CONOSCENZA_MOD               NUMBER
)
ON COMMIT DELETE ROWS
/
CREATE GLOBAL TEMPORARY TABLE TEMP_STORICO_DOC_DATI_SCARTO
(
  ID                   NUMBER,
  ID_DOCUMENTO         NUMBER,
  LOG_ID_DOCUMENTO     NUMBER,
  LOG_DATA             DATE,
  LOG_UTENTE           VARCHAR2(20),
  ID_VALORE_LOG        NUMBER,
  STATO                VARCHAR2(255),
  STATO_MOD            NUMBER(1)                DEFAULT 0,
  DATA_STATO           DATE,
  DATA_STATO_MOD       NUMBER(1)                DEFAULT 0,
  NULLA_OSTA           VARCHAR2(255),
  NULLA_OSTA_MOD       NUMBER(1)                DEFAULT 0,
  DATA_NULLA_OSTA      DATE,
  DATA_NULLA_OSTA_MOD  NUMBER(1)                DEFAULT 0
)
ON COMMIT DELETE ROWS
/
drop table TEMP_STORICO_PROT
/
CREATE GLOBAL TEMPORARY TABLE TEMP_STORICO_PROT
(
  ID                    NUMBER                  NOT NULL,
  ID_DOCUMENTO          NUMBER                  NOT NULL,
  IDRIF                 VARCHAR2(20),
  LOG_ID_DOCUMENTO      NUMBER                  NOT NULL,
  LOG_DATA              DATE,
  LOG_UTENTE            VARCHAR2(20),
  ID_VALORE_LOG         NUMBER,
  OGGETTO               VARCHAR2(4000),
  MODALITA              VARCHAR2(4000),
  CLASS_COD             VARCHAR2(4000),
  FASCICOLO_ANNO        NUMBER,
  FASCICOLO_NUMERO      VARCHAR2(4000),
  DATA_ARRIVO           DATE,
  DATA_DOCUMENTO        VARCHAR2(4000),
  NUMERO_DOCUMENTO      VARCHAR2(4000),
  RISERVATO             VARCHAR2(4000),
  OGGETTO_MOD           NUMBER,
  MODALITA_MOD          NUMBER,
  CLASS_COD_MOD         NUMBER,
  FASCICOLO_ANNO_MOD    NUMBER,
  FASCICOLO_NUMERO_MOD  NUMBER,
  DATA_ARRIVO_MOD       NUMBER,
  DATA_DOCUMENTO_MOD    NUMBER,
  NUMERO_DOCUMENTO_MOD  NUMBER,
  RISERVATO_MOD         NUMBER
)
ON COMMIT DELETE ROWS
/