--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327_2.agp_scarico_ipa_recreate

CREATE TABLE AGP_SCARICO_IPA
(
  ID_SCARICO_IPA        NUMBER,
  NOME_CRITERIO         VARCHAR2(1000),
  IMPORT_TUTTE_AMM      CHAR(1)            DEFAULT 'Y',
  IMPORT_UNITA          CHAR(1)            DEFAULT 'Y',
  CODICE_AMM            VARCHAR2(1000),
  DESCRIZIONE_AMM       VARCHAR2(1000),
  TIPOLOGIA_ENTE        VARCHAR2(1000),
  CODICE_REGIONE_AMM    NUMBER,
  CODICE_PROVINCIA_AMM  NUMBER,
  IMPORT_TUTTE_AOO      CHAR(1)            DEFAULT 'Y',
  CODICE_REGIONE_AOO    NUMBER,
  CODICE_PROVINCIA_AOO  NUMBER,
  CODICE_AOO            VARCHAR2(1000),
  ID_JOB_CONFIG         NUMBER,
  VERSION               NUMBER,
  DATA_INS              DATE,
  DATA_UPD              DATE,
  UTENTE_INS            VARCHAR2(255),
  UTENTE_UPD            VARCHAR2(255),
  VALIDO                CHAR(1)            DEFAULT 'Y',
  ID_ENTE               NUMBER,
  DESCRIZIONE_AOO       VARCHAR2(1000),
  STRINGA_CRON          VARCHAR2(255),
  NUMERO_GIORNI         NUMBER,
  ORA_ESECUZIONE        VARCHAR2(255),
  MINUTI_ESECUZIONE     VARCHAR2(255)
)
/

ALTER TABLE AGP_SCARICO_IPA ADD (
  CONSTRAINT AGP_SCARICO_IPA_PK
  PRIMARY KEY
  (ID_SCARICO_IPA)
  ENABLE VALIDATE)
/
