--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.4.agp_abilitazioni_smistamento_alter
CREATE INDEX AGP_ABSM_ENTI_FK ON AGP_ABILITAZIONI_SMISTAMENTO
(ID_ENTE)
/
ALTER TABLE AGP_ABILITAZIONI_SMISTAMENTO
 ADD CONSTRAINT AGP_ABSM_ENTI_FK
  FOREIGN KEY (ID_ENTE) 
  REFERENCES GDO_ENTI (ID_ENTE)
/