--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.5.agp_tipi_accesso_civico_alter
CREATE INDEX AGP_TACI_ENTI_FK ON AGP_TIPI_ACCESSO_CIVICO
(ID_ENTE)
/
ALTER TABLE AGP_TIPI_ACCESSO_CIVICO
 ADD CONSTRAINT AGP_TACI_ENTI_FK
  FOREIGN KEY (ID_ENTE)
  REFERENCES GDO_ENTI (ID_ENTE)
/