--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.7.agp_tipi_richiedente_accesso_alter
CREATE INDEX AGP_TRAC_ENTI_FK ON AGP_TIPI_RICHIEDENTE_ACCESSO
(ID_ENTE)
/
ALTER TABLE AGP_TIPI_RICHIEDENTE_ACCESSO
 ADD CONSTRAINT AGP_TRAC_ENTI_FK
  FOREIGN KEY (ID_ENTE)
  REFERENCES GDO_ENTI (ID_ENTE)
/