--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.10.wkf_diz_pulsanti_alter
CREATE INDEX WKF_DIPU_DTOG_FK ON WKF_DIZ_PULSANTI
(TIPO_OGGETTO)
/
ALTER TABLE WKF_DIZ_PULSANTI
 ADD CONSTRAINT WKF_DIPU_DTOG_FK
  FOREIGN KEY (TIPO_OGGETTO)
  REFERENCES WKF_DIZ_TIPI_OGGETTO (CODICE)
/