--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.11.wkf_diz_pulsanti_azioni_alter
CREATE INDEX WKF_DPAZ_DIPU_FK ON WKF_DIZ_PULSANTI_AZIONI
(ID_PULSANTE)
/
ALTER TABLE WKF_DIZ_PULSANTI_AZIONI
 ADD CONSTRAINT WKF_DPAZ_DIPU_FK
  FOREIGN KEY (ID_PULSANTE)
  REFERENCES WKF_DIZ_PULSANTI (ID_PULSANTE)
/