--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.12.wkf_diz_attori_alter
CREATE INDEX WKF_DIAT_DTOG_FK ON WKF_DIZ_ATTORI
(TIPO_OGGETTO)
/
ALTER TABLE WKF_DIZ_ATTORI
 ADD CONSTRAINT WKF_DIAT_DTOG_FK
  FOREIGN KEY (TIPO_OGGETTO)
  REFERENCES WKF_DIZ_TIPI_OGGETTO (CODICE)
/