--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.13.wkf_cfg_step_azioni_in_alter
CREATE INDEX WKF_CSAI_CFST_FK ON WKF_CFG_STEP_AZIONI_IN
(ID_CFG_STEP)
/
ALTER TABLE WKF_CFG_STEP_AZIONI_IN
 ADD CONSTRAINT WKF_CSAI_CFST_FK
  FOREIGN KEY (ID_CFG_STEP)
  REFERENCES WKF_CFG_STEP (ID_CFG_STEP)
/