--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.14.wkf_cfg_step_azioni_out_alter

CREATE INDEX WKF_CSAO_CFST_FK ON WKF_CFG_STEP_AZIONI_OUT
(ID_CFG_STEP)
/
ALTER TABLE WKF_CFG_STEP_AZIONI_OUT
 ADD CONSTRAINT WKF_CSAO_CFST_FK
  FOREIGN KEY (ID_CFG_STEP)
  REFERENCES WKF_CFG_STEP (ID_CFG_STEP)
/