--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.15.gdo_allegati_alter
CREATE INDEX GDO_ALLE_TIAL_FK ON GDO_ALLEGATI
(ID_TIPO_ALLEGATO)
/
ALTER TABLE GDO_ALLEGATI
 ADD CONSTRAINT GDO_ALLE_TIAL_FK
  FOREIGN KEY (ID_TIPO_ALLEGATO)
  REFERENCES GDO_TIPI_ALLEGATO (ID_TIPO_DOCUMENTO)
/