--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.16.wkf_cfg_competenze_alter failOnError:false
CREATE INDEX WKF_CFC_DTOG_FK ON WKF_CFG_COMPETENZE
(TIPO_OGGETTO)
/
ALTER TABLE WKF_CFG_COMPETENZE
 ADD CONSTRAINT WKF_CFC_DTOG_FK
  FOREIGN KEY (TIPO_OGGETTO)
  REFERENCES WKF_DIZ_TIPI_OGGETTO (CODICE)
/