--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200327.18.agp_protocolli_alter failOnError:false
CREATE INDEX AGP_PROT_DDSC_FK ON AGP_PROTOCOLLI
(ID_PROTOCOLLO_DATI_SCARTO)
/
ALTER TABLE AGP_PROTOCOLLI
 ADD CONSTRAINT AGP_PROT_DDSC_FK
  FOREIGN KEY (ID_PROTOCOLLO_DATI_SCARTO)
  REFERENCES AGP_DOCUMENTI_DATI_SCARTO (ID_DOCUMENTO_DATI_SCARTO)
/
CREATE INDEX AGP_PROT_MIRI_FK ON AGP_PROTOCOLLI
(ID_MODALITA_INVIO_RICEZIONE)
/
ALTER TABLE AGP_PROTOCOLLI
 ADD CONSTRAINT AGP_PROT_MIRI_FK
  FOREIGN KEY (ID_MODALITA_INVIO_RICEZIONE)
  REFERENCES AGS_MODALITA_INVIO_RICEZIONE (ID_MODALITA_INVIO_RICEZIONE)
/
