--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200827_26.agp_documenti_titolario_log

CREATE TABLE AGP_DOCUMENTI_TITOLARIO_LOG
(
   ID_DOCUMENTO_TITOLARIO   NUMBER NOT NULL,
   REV                      NUMBER (19),
   REVTYPE                  NUMBER (3),
   REVEND                   NUMBER (19),
   ID_DOCUMENTO             NUMBER,
   ID_DOCUMENTO_MOD         NUMBER (1) DEFAULT 0 NOT NULL,
   ID_CLASSIFICAZIONE       NUMBER,
   ID_CLASSIFICAZIONE_MOD   NUMBER (1) DEFAULT 0 NOT NULL,
   ID_FASCICOLO             NUMBER,
   ID_FASCICOLO_MOD         NUMBER (1) DEFAULT 0 NOT NULL,
   VALIDO                   CHAR (1),
   VALIDO_MOD               NUMBER (1) DEFAULT 0 NOT NULL,
   UTENTE_INS               VARCHAR2 (255 BYTE),
   UTENTE_INS_MOD           NUMBER (1) DEFAULT 0 NOT NULL,
   DATA_INS                 DATE,
   DATE_CREATED_MOD         NUMBER (1) DEFAULT 0 NOT NULL,
   UTENTE_UPD               VARCHAR2 (255 BYTE),
   UTENTE_UPD_MOD           NUMBER (1) DEFAULT 0 NOT NULL,
   DATA_UPD                 DATE,
   LAST_UPDATED_MOD         NUMBER (1) DEFAULT 0 NOT NULL
)
/


CREATE UNIQUE INDEX AGP_DOCUMENTI_TITOLARIO_LOG_PK
   ON AGP_DOCUMENTI_TITOLARIO_LOG (ID_DOCUMENTO_TITOLARIO, REV)
/

ALTER TABLE AGP_DOCUMENTI_TITOLARIO_LOG ADD (
  CONSTRAINT AGP_DOCUMENTI_TITOLARIO_LOG_PK
  PRIMARY KEY
  (ID_DOCUMENTO_TITOLARIO, REV)
  USING INDEX AGP_DOCUMENTI_TITOLARIO_LOG_PK
  ENABLE VALIDATE)
/