--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200828_27.AGP_MSG_INVIATI_DATI_PROT

drop TABLE AGP_MSG_INVIATI_DATI_PROT
/

CREATE TABLE AGP_MSG_INVIATI_DATI_PROT
(
  ID_DOCUMENTO              NUMBER              NOT NULL,
  ID_MESSAGGIO_SI4CS        NUMBER,
  OGGETTO                   VARCHAR2(2000 BYTE),
  TESTO                     CLOB,
  MITTENTE                  VARCHAR2(2000 BYTE),
  DESTINATARI               CLOB,
  DESTINATARI_CONOSCENZA    CLOB,
  DESTINATARI_NASCOSTI      CLOB,
  TAGMAIL                   VARCHAR2(255 BYTE),
  MITTENTE_AMMINISTRAZIONE  VARCHAR2(255 BYTE),
  MITTENTE_AOO              VARCHAR2(255 BYTE),
  MITTENTE_UO               VARCHAR2(255 BYTE),
  STATO_SPEDIZIONE          VARCHAR2(240 BYTE)  DEFAULT 'READYTOSEND',
  DATA_SPEDIZIONE           DATE,
  ACCETTAZIONE              CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  NON_ACCETTAZIONE          CHAR(1 BYTE)        DEFAULT 'N'                   NOT NULL
)
/

CREATE UNIQUE INDEX AGP_MSG_INVIATI_DATI_PROT_PK ON AGP_MSG_INVIATI_DATI_PROT
(ID_DOCUMENTO)
/

ALTER TABLE AGP_MSG_INVIATI_DATI_PROT ADD (
  CONSTRAINT AGP_MSG_INVIATI_DATI_PROT_PK
  PRIMARY KEY
  (ID_DOCUMENTO)
  USING INDEX AGP_MSG_INVIATI_DATI_PROT_PK
  ENABLE VALIDATE)
/

CREATE UNIQUE INDEX AGP_MSG_INVIATI_DATI_PROT_UK ON AGP_MSG_INVIATI_DATI_PROT
(ID_MESSAGGIO_SI4CS)
/

ALTER TABLE AGP_MSG_INVIATI_DATI_PROT ADD (
  CONSTRAINT AGP_MSG_INVIATI_DATI_PROT_UK
  UNIQUE (ID_MESSAGGIO_SI4CS)
  USING INDEX AGP_MSG_INVIATI_DATI_PROT_UK)
/

ALTER TABLE AGP_MSG_INVIATI_DATI_PROT ADD (
  CONSTRAINT AGP_MIDA_DOCU_FK
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES GDO_DOCUMENTI (ID_DOCUMENTO))
/

ALTER TABLE AGP_MSG_INVIATI_DATI_PROT ADD (
  CONSTRAINT AGP_MSG_INV_DATI_PROT_STATO_CC
  CHECK (STATO_SPEDIZIONE IN ('READYTOSEND', 'SENDING', 'SENTOK', 'SENTFAILED') AND STATO_SPEDIZIONE = UPPER(STATO_SPEDIZIONE))
  ENABLE VALIDATE)
/

CREATE TABLE AGP_MSG_INVIATI_DATI_PROT_LOG
(
  ID_DOCUMENTO          NUMBER(19),
  REV                   NUMBER(19),
  STATO_SPEDIZIONE      VARCHAR2(240 BYTE),
  STATO_SPEDIZIONE_MOD  NUMBER(1)               DEFAULT 0                     NOT NULL,
  ACCETTAZIONE          CHAR(1 BYTE),
  ACCETTAZIONE_MOD      NUMBER(1)               DEFAULT 0                     NOT NULL,
  NON_ACCETTAZIONE      CHAR(1 BYTE),
  NON_ACCETTAZIONE_MOD  NUMBER(1)               DEFAULT 0                     NOT NULL,
  DATA_SPEDIZIONE       DATE,
  DATA_SPEDIZIONE_MOD   NUMBER(1)               DEFAULT 0                     NOT NULL
)
/


CREATE UNIQUE INDEX AGP_MSG_INV_DATI_PROT_LOG_PK ON AGP_MSG_INVIATI_DATI_PROT_LOG
(ID_DOCUMENTO, REV)
/

ALTER TABLE AGP_MSG_INVIATI_DATI_PROT_LOG ADD (
  CONSTRAINT AGP_MSG_INV_DATI_PROT_LOG_PK
  PRIMARY KEY
  (ID_DOCUMENTO, REV)
  USING INDEX AGP_MSG_INV_DATI_PROT_LOG_PK)
/
