--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20200828_30.ags_filtri_documenti_esterni

CREATE TABLE AGS_FILTRI_DOCUMENTI_ESTERNI
(
  CHIAVE                  VARCHAR2(255 BYTE),
  DESCRIZIONE             VARCHAR2(4000 BYTE),
  CAMPO_DATA_ORDINAMENTO  VARCHAR2(255 BYTE)
)
/

CREATE UNIQUE INDEX AGS_FILTRI_DOC_ESTERNI_PK ON AGS_FILTRI_DOCUMENTI_ESTERNI
(CHIAVE)
/

ALTER TABLE AGS_FILTRI_DOCUMENTI_ESTERNI ADD (
  CONSTRAINT AGS_FILTRI_DOC_ESTERNI_PK
  PRIMARY KEY
  (CHIAVE)
  USING INDEX AGS_FILTRI_DOC_ESTERNI_PK)
/
