--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20201007_49.agp_stati_scarto_view_to_table
CREATE TABLE AGP_STATI_SCARTO_TABLE
(
  CODICE       VARCHAR2(255 BYTE),
  DESCRIZIONE  VARCHAR2(4000 BYTE),
  CODICE_GDM   VARCHAR2(255 BYTE)
)
/

CREATE UNIQUE INDEX AGP_STATI_SCARTO_PK ON AGP_STATI_SCARTO_TABLE
(CODICE)
/

ALTER TABLE AGP_STATI_SCARTO_TABLE ADD (
  CONSTRAINT AGP_STATI_SCARTO_PK
  PRIMARY KEY
  (CODICE)
  USING INDEX AGP_STATI_SCARTO_PK
  ENABLE VALIDATE)
/

insert into AGP_STATI_SCARTO_TABLE (CODICE, DESCRIZIONE, CODICE_GDM)
SELECT
CODICE, DESCRIZIONE, CODICE_GDM
FROM AGP_STATI_SCARTO
/
commit
/

drop view AGP_STATI_SCARTO
/

rename AGP_STATI_SCARTO_TABLE to AGP_STATI_SCARTO
/