--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20201008_50.AGP_SCHEMI_PROT_INTEGRAZIONI_alter
ALTER TABLE AGP_SCHEMI_PROT_INTEGRAZIONI
drop CONSTRAINT AGP_SCHEMA_PROT_INTEGRAZIO_UK
/
drop index AGP_SCHEMA_PROT_INTEGRAZIO_UK
/
ALTER TABLE AGP_SCHEMI_PROT_INTEGRAZIONI
    ADD (tipo_pratica VARCHAR2 (1000) )
/
CREATE UNIQUE INDEX AGP_SCHEMI_PROT_INTEGRAZIO_UK ON AGP_SCHEMI_PROT_INTEGRAZIONI
(APPLICATIVO, ID_SCHEMA_PROTOCOLLO, TIPO_PRATICA)
/
ALTER TABLE AGP_SCHEMI_PROT_INTEGRAZIONI ADD (
 CONSTRAINT AGP_SCHEMI_PROT_INTEGRAZIO_UK
  UNIQUE (APPLICATIVO, ID_SCHEMA_PROTOCOLLO, TIPO_PRATICA)
  USING INDEX AGP_SCHEMI_PROT_INTEGRAZIO_UK
  ENABLE VALIDATE)
/