--liquibase formatted sql
--changeset mmalferrari:4.1.0.0_20201020_53.agp_tipi_protocollo_alter

ALTER TABLE AGP_TIPI_PROTOCOLLO
   DROP CONSTRAINT AGP_TIPR_CATEGORIA_CC
/

ALTER TABLE AGP_TIPI_PROTOCOLLO ADD (
  CONSTRAINT AGP_TIPR_CATEGORIA_CC
  CHECK (CATEGORIA IN ('LETTERA','PROTOCOLLO','PEC','EMERGENZA','PROVVEDIMENTO','REGISTRO_GIORNALIERO','DA_NON_PROTOCOLLARE', 'DOCUMENTO_ESTERNO'))
)
/