
package it.finmatica.affarigenerali.ducd.pec;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PecSOAPImplService", targetNamespace = "http://pec.ducd.affarigenerali.finmatica.it", wsdlLocation = "http://svi-ag-fin-as1.finmatica.local:9080/ducd/services/PecSOAPImpl?wsdl")
public class PecSOAPImplService
    extends Service
{

    private final static URL PECSOAPIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PECSOAPIMPLSERVICE_EXCEPTION;
    private final static QName PECSOAPIMPLSERVICE_QNAME = new QName("http://pec.ducd.affarigenerali.finmatica.it", "PecSOAPImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://svi-ag-fin-as1.finmatica.local:9080/ducd/services/PecSOAPImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PECSOAPIMPLSERVICE_WSDL_LOCATION = url;
        PECSOAPIMPLSERVICE_EXCEPTION = e;
    }

    public PecSOAPImplService() {
        super(__getWsdlLocation(), PECSOAPIMPLSERVICE_QNAME);
    }

    public PecSOAPImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PECSOAPIMPLSERVICE_QNAME, features);
    }

    public PecSOAPImplService(URL wsdlLocation) {
        super(wsdlLocation, PECSOAPIMPLSERVICE_QNAME);
    }

    public PecSOAPImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PECSOAPIMPLSERVICE_QNAME, features);
    }

    public PecSOAPImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PecSOAPImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PecSOAPImpl
     */
    @WebEndpoint(name = "PecSOAPImpl")
    public PecSOAPImpl getPecSOAPImpl() {
        return super.getPort(new QName("http://pec.ducd.affarigenerali.finmatica.it", "PecSOAPImpl"), PecSOAPImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PecSOAPImpl
     */
    @WebEndpoint(name = "PecSOAPImpl")
    public PecSOAPImpl getPecSOAPImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://pec.ducd.affarigenerali.finmatica.it", "PecSOAPImpl"), PecSOAPImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PECSOAPIMPLSERVICE_EXCEPTION!= null) {
            throw PECSOAPIMPLSERVICE_EXCEPTION;
        }
        return PECSOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
