--liquibase formatted sql
--changeset esasdelli:AGSPR_VIEW_AGP_PROTOCOLLI_DATI_SCARTO runOnChange:true stripComments:false

  CREATE OR REPLACE FORCE VIEW "AGP_PROTOCOLLI_DATI_SCARTO" ("ID_PROTOCOLLO_DATI_SCARTO", "STATO", "DATA_STATO", "NULLA_OSTA", "DATA_NULLA_OSTA", "UTENTE_INS", "DATA_INS", "UTENTE_UPD", "DATA_UPD", "VERSION") AS 
  SELECT 
ID_DOCUMENTO_DATI_SCARTO ID_PROTOCOLLO_DATI_SCARTO, STATO, DATA_STATO, 
   NULLA_OSTA, DATA_NULLA_OSTA, UTENTE_INS, 
   DATA_INS, UTENTE_UPD, DATA_UPD, 
   VERSION
FROM AGP_DOCUMENTI_DATI_SCARTO
/
