--liquibase formatted sql
--changeset esasdelli:AGSPR_VIEW_AGP_V_PROTOCOLLI runOnChange:true stripComments:false

  CREATE OR REPLACE FORCE VIEW "AGP_V_PROTOCOLLI" ("ID_DOCUMENTO", "ANNO", "TIPO_REGISTRO", "NUMERO", "DATA", "ID_TIPO_PROTOCOLLO", "MOVIMENTO", "OGGETTO", "DATA_VERIFICA", "ESITO_VERIFICA", "ANNULLATO", "CONTROLLO_FUNZIONARIO", "NOTE", "NOTE_TRASMISSIONE", "IDRIF", "ID_CLASSIFICAZIONE", "ID_FASCICOLO", "DATA_REDAZIONE", "ID_SCHEMA_PROTOCOLLO", "ID_MODALITA_INVIO_RICEZIONE", "DATA_ANNULLAMENTO", "UTENTE_ANNULLAMENTO", "PROVVEDIMENTO_ANNULLAMENTO", "CONTROLLO_FIRMATARIO", "DATA_COMUNICAZIONE", "DATA_DOCUMENTO_ESTERNO", "NUMERO_DOCUMENTO_ESTERNO", "STATO_ARCHIVIO", "DATA_STATO_ARCHIVIO", "CODICE_RACCOMANDATA", "ID_PROTOCOLLO_DATI_SCARTO", "ID_PROTOCOLLO_DATI_INTEROP", "CAMPI_PROTETTI", "STATO", "STATO_FIRMA", "STATO_CONSERVAZIONE", "ID_ENGINE_ITER", "ID_DOCUMENTO_ESTERNO", "ID_ENTE", "TIPO_OGGETTO", "VALIDO", "UTENTE_INS", "DATA_INS", "UTENTE_UPD", "DATA_UPD", "RISERVATO") AS 
  SELECT p."ID_DOCUMENTO",p."ANNO",p."TIPO_REGISTRO",p."NUMERO",p."DATA",p."ID_TIPO_PROTOCOLLO",p."MOVIMENTO",p."OGGETTO",p."DATA_VERIFICA",p."ESITO_VERIFICA",p."ANNULLATO",p."CONTROLLO_FUNZIONARIO",p."NOTE",p."NOTE_TRASMISSIONE",p."IDRIF",p."ID_CLASSIFICAZIONE",p."ID_FASCICOLO",p."DATA_REDAZIONE",p."ID_SCHEMA_PROTOCOLLO",p."ID_MODALITA_INVIO_RICEZIONE",p."DATA_ANNULLAMENTO",p."UTENTE_ANNULLAMENTO",p."PROVVEDIMENTO_ANNULLAMENTO",p."CONTROLLO_FIRMATARIO",p."DATA_COMUNICAZIONE",p."DATA_DOCUMENTO_ESTERNO",p."NUMERO_DOCUMENTO_ESTERNO",p."STATO_ARCHIVIO",p."DATA_STATO_ARCHIVIO",p."CODICE_RACCOMANDATA",p."ID_PROTOCOLLO_DATI_SCARTO",p."ID_PROTOCOLLO_DATI_INTEROP",p."CAMPI_PROTETTI",
       d.STATO,
       d.STATO_FIRMA,
       d.STATO_CONSERVAZIONE,
       d.ID_ENGINE_ITER,
       d.ID_DOCUMENTO_ESTERNO,
       d.ID_ENTE,
       d.TIPO_OGGETTO,
       d.VALIDO,
       d.UTENTE_INS,
       d.DATA_INS,
       d.UTENTE_UPD,
       d.DATA_UPD,
       d.RISERVATO
  FROM agp_protocolli p, gdo_documenti d
 WHERE P.ID_DOCUMENTO = D.ID_DOCUMENTO
/
