--liquibase formatted sql
--changeset esasdelli:AGSPR_VIEW_AGP_PROTOCOLLI_DATI_SCARTO_LOG runOnChange:true stripComments:false

  CREATE OR REPLACE FORCE VIEW "AGP_PROTOCOLLI_DATI_SCARTO_LOG" ("ID_PROTOCOLLO_DATI_SCARTO", "REV", "REVTYPE", "REVEND", "STATO", "STATO_MOD", "DATA_STATO", "DATA_STATO_MOD", "NULLA_OSTA", "NULLA_OSTA_MOD", "DATA_NULLA_OSTA", "DATA_NULLA_OSTA_MOD", "UTENTE_INS", "UTENTE_INS_MOD", "DATA_INS", "DATE_CREATED_MOD", "UTENTE_UPD", "UTENTE_UPD_MOD", "DATA_UPD", "LAST_UPDATED_MOD") AS 
  SELECT 
ID_DOCUMENTO_DATI_SCARTO ID_PROTOCOLLO_DATI_SCARTO, REV, REVTYPE, 
   REVEND, STATO, STATO_MOD, 
   DATA_STATO, DATA_STATO_MOD, NULLA_OSTA, 
   NULLA_OSTA_MOD, DATA_NULLA_OSTA, DATA_NULLA_OSTA_MOD, 
   UTENTE_INS, UTENTE_INS_MOD, DATA_INS, 
   DATE_CREATED_MOD, UTENTE_UPD, UTENTE_UPD_MOD, 
   DATA_UPD, LAST_UPDATED_MOD
FROM AGP_DOCUMENTI_DATI_SCARTO_LOG
/
