--liquibase formatted sql
--changeset mmalferrari:AS4_V_ANAGRAFICI_RECAPITI runOnChange:true stripComments:false

CREATE OR REPLACE FORCE VIEW AS4_V_ANAGRAFICI_RECAPITI
(
   ID_SOGGETTO,
   CODICE_FISCALE,
   PARTITA_IVA,
   ID_RECAPITO,
   ID_CONTATTO
)
AS
   SELECT ana.NI AS ID_SOGGETTO,
          ana.CODICE_FISCALE,
          ANA.PARTITA_IVA,
          A4VR.ID_RECAPITO,
          A4VC.ID_CONTATTO
     FROM AS4_V_ANAGRAFICI ANA
          JOIN AS4_V_RECAPITI A4VR ON ANA.NI = A4VR.NI
          LEFT OUTER JOIN AS4_V_CONTATTI A4VC
             ON A4VR.ID_RECAPITO = A4VC.ID_RECAPITO
/