--liquibase formatted sql
--changeset esasdelli:AGSPR_VIEW_GDO_TIPI_REGISTRO runOnChange:true stripComments:false

  CREATE OR REPLACE FORCE VIEW "GDO_TIPI_REGISTRO" ("TIPO_REGISTRO", "COMMENTO", "EMERGENZA", "CHIUSURA_AUTOMATICA", "RINNOVO_AUTOMATICO", "REGISTRO_ESTERNO", "ID_ENTE", "UTENTE_INS", "DATA_INS", "UTENTE_UPD", "DATA_UPD", "VALIDO", "VERSION") AS 
  SELECT TIPO_REGISTRO,
       DESCRIZIONE_TIPO_REGISTRO,
       EMERGENZA,
       'N' CHIUSURA_AUTOMATICA,
       'N' RINNOVO_AUTOMATICO,
       TO_CHAR (NULL) REGISTRO_ESTERNO,
       ENTI.ID_ENTE,
       DOCU.UTENTE_AGGIORNAMENTO UTENTE_INS,
       DOCU.DATA_AGGIORNAMENTO DATA_INS,
       DOCU.UTENTE_AGGIORNAMENTO UTENTE_UPD,
       DOCU.DATA_AGGIORNAMENTO DATA_UPD,
       CAST (
          DECODE (NVL (docu.stato_documento, 'BO'), 'BO', 'Y', 'N') AS CHAR (1))
          VALIDO,
       0
  FROM (SELECT get_id_tipo_registro (tipo_registro) ID_DOCUMENTO
          FROM (  SELECT DISTINCT REGI.TIPO_REGISTRO
                    FROM GDM_SEG_REGISTRI REGI
                GROUP BY REGI.TIPO_REGISTRO)) TIRE,
       GDM_SEG_REGISTRI REGI,
       GDM_DOCUMENTI DOCU,
       GDO_ENTI ENTI
 WHERE     REGI.ID_DOCUMENTO = TIRE.ID_DOCUMENTO
       AND DOCU.ID_DOCUMENTO = REGI.ID_DOCUMENTO
       AND ENTI.AMMINISTRAZIONE = REGI.CODICE_AMMINISTRAZIONE
       AND ENTI.AOO = REGI.CODICE_AOO
       AND ENTI.OTTICA = GDM_AG_PARAMETRO.GET_VALORE (
                            'SO_OTTICA_PROT',
                            REGI.CODICE_AMMINISTRAZIONE,
                            REGI.CODICE_AOO,
                            '')
/
