--liquibase formatted sql
--changeset esasdelli:AGSPR_VIEW_SEG_ANAGRAFICI runOnChange:true stripComments:false

  CREATE OR REPLACE FORCE VIEW "SEG_ANAGRAFICI" ("DENOMINAZIONE", "COGNOME", "NOME", "CODICE_FISCALE", "PARTITA_IVA", "INDIRIZZO", "INDIRIZZO_COMPLETO", "CAP", "COMUNE", "PROVINCIA_SIGLA", "EMAIL", "FAX", "TIPO_SOGGETTO", "ANAGRAFICA", "COD_AMM", "COD_AOO", "COD_UO", "NI", "DAL", "AL", "TIPO_INDIRIZZO", "CF_ESTERO", "ID_TIPO_RECAPITO", "TIPO_SPEDIZIONE") AS 
  SELECT "DENOMINAZIONE",
          "COGNOME",
          "NOME",
          "CODICE_FISCALE",
          "PARTITA_IVA",
          "INDIRIZZO_PER_SEGNATURA",
          "INDIRIZZO",
          "CAP_PER_SEGNATURA",
          "COMUNE_PER_SEGNATURA",
          "PROVINCIA_PER_SEGNATURA",
          "EMAIL",
          "FAX",
          "TIPO_SOGGETTO",
          'Soggetto' "ANAGRAFICA",
          "COD_AMM",
          "COD_AOO",
          "COD_UO",
          TO_NUMBER ("NI"),
          "DAL",
          "AL",
          "DESCRIZIONE_TIPO_RECAPITO",
          "CF_ESTERO",
          "ID_TIPO_RECAPITO",
          "TIPO_SPEDIZIONE"
     FROM gdm_seg_anagrafici_as4
   UNION ALL
   SELECT "DENOMINAZIONE",
          "COGNOME",
          "NOME",
          "CODICE_FISCALE",
          "PARTITA_IVA",
          "INDIRIZZO",
          "INDIRIZZO_COMPLETO",
          "CAP",
          "COMUNE",
          "PROVINCIA_SIGLA",
          "EMAIL",
          "FAX",
          "TIPO_SOGGETTO",
          'Amministrazione' "ANAGRAFICA",
          "COD_AMM",
          "COD_AOO",
          "COD_UO",
          "NI",
          "DAL",
          "AL",
          "TIPO_INDIRIZZO",
          NULL,
          NULL,
          NULL
     FROM seg_anagrafici_so4
   UNION ALL
   SELECT "DENOMINAZIONE",
          "COGNOME",
          "NOME",
          "CODICE_FISCALE",
          "PARTITA_IVA",
          "INDIRIZZO",
          "INDIRIZZO_COMPLETO",
          "CAP",
          "COMUNE",
          "PROVINCIA_SIGLA",
          "EMAIL",
          "FAX",
          "TIPO_SOGGETTO",
          "ANAGRAFICA",
          "COD_AMM",
          "COD_AOO",
          "COD_UO",
          "NI",
          "DAL",
          "AL",
          "TIPO_INDIRIZZO",
          "CF_ESTERO",
          NULL,
          NULL
     FROM seg_anagrafici_altri
/
