--liquibase formatted sql
--changeset esasdelli:AGSPR_VIEW_SEG_ANAGRAFICI_BASE runOnChange:true stripComments:false

  CREATE OR REPLACE FORCE VIEW "SEG_ANAGRAFICI_BASE" ("DENOMINAZIONE", "COGNOME", "NOME", "CODICE_FISCALE", "PARTITA_IVA", "INDIRIZZO", "INDIRIZZO_COMPLETO", "CAP", "COMUNE", "PROVINCIA_SIGLA", "EMAIL", "FAX", "TIPO_SOGGETTO", "ANAGRAFICA", "COD_AMM", "COD_AOO", "COD_UO", "NI", "DAL", "AL", "TIPO_INDIRIZZO", "ID_RECAPITO", "ID_CONTATTO", "CF_ESTERO", "ID_TIPO_RECAPITO", "TIPO_SPEDIZIONE") AS 
  SELECT denominazione,
          cognome_per_segnatura,
          nome_per_segnatura,
          cf_per_segnatura,
          "PARTITA_IVA",
          indirizzo_per_segnatura,
          indirizzo,
          cap_per_segnatura,
          "COMUNE",
          provincia_per_segnatura,
          "EMAIL",
          "FAX",
          "TIPO_SOGGETTO",
          'Soggetto' "ANAGRAFICA",
          "COD_AMM",
          "COD_AOO",
          "COD_UO",
          "NI",
          "DAL",
          "AL",
          descrizione_tipo_recapito,
          ID_RECAPITO,
          ID_CONTATTO,
          cf_estero,
          ID_TIPO_RECAPITO,
          TIPO_SPEDIZIONE
     FROM gdm_seg_anagrafici_as4
   UNION ALL
   SELECT "DENOMINAZIONE",
          "COGNOME",
          "NOME",
          "CODICE_FISCALE",
          "PARTITA_IVA",
          "INDIRIZZO",
          "INDIRIZZO_COMPLETO",
          "CAP",
          "COMUNE",
          "PROVINCIA_SIGLA",
          "EMAIL",
          "FAX",
          "TIPO_SOGGETTO",
          "ANAGRAFICA",
          "COD_AMM",
          "COD_AOO",
          "COD_UO",
          TO_CHAR (NI),
          "DAL",
          "AL",
          "TIPO_INDIRIZZO",
          ID_RECAPITO,
          ID_CONTATTO,
          NULL,
          NULL,
          NULL
     FROM (SELECT "DENOMINAZIONE",
                  "COGNOME",
                  "NOME",
                  "CODICE_FISCALE",
                  "PARTITA_IVA",
                  "INDIRIZZO",
                  "INDIRIZZO_COMPLETO",
                  "CAP",
                  "COMUNE",
                  "PROVINCIA_SIGLA",
                  "EMAIL",
                  "FAX",
                  "TIPO_SOGGETTO",
                  'Amministrazione' "ANAGRAFICA",
                  "COD_AMM",
                  "COD_AOO",
                  "COD_UO",
                  "NI",
                  "DAL",
                  "AL",
                  "TIPO_INDIRIZZO",
                  NULL ID_RECAPITO,
                  NULL ID_CONTATTO
             FROM seg_anagrafici_so4)
/
