--liquibase formatted sql
--changeset esasdelli:AGSPR_VIEW_SEG_ANAGRAFICI_SO4 runOnChange:true stripComments:false

  CREATE OR REPLACE FORCE VIEW "SEG_ANAGRAFICI_SO4" ("DENOMINAZIONE", "COGNOME", "NOME", "CODICE_FISCALE", "PARTITA_IVA", "INDIRIZZO", "INDIRIZZO_COMPLETO", "CAP", "COMUNE", "PROVINCIA_SIGLA", "EMAIL", "FAX", "TIPO_SOGGETTO", "ANAGRAFICA", "COD_AMM", "COD_AOO", "COD_UO", "NI", "DAL", "AL", "TIPO_INDIRIZZO") AS 
  SELECT DENOMINAZIONE DENOMINAZIONE,
       COGNOME_PER_SEGNATURA COGNOME,
       NOME_PER_SEGNATURA NOME,
       CF_PER_SEGNATURA CODICE_FISCALE,
       PI PARTITA_IVA,
       INDIRIZZO_PER_SEGNATURA INDIRIZZO,
       indirizzo INDIRIZZO_COMPLETO,
       CAP_PER_SEGNATURA CAP,
       COMUNE_PER_SEGNATURA COMUNE,
       PROVINCIA_PER_SEGNATURA PROVINCIA_SIGLA,
       EMAIL,
       FAX,
       2 TIPO_SOGGETTO,
          'Amministrazione'
       || DECODE (SEG_AMM_AOO_UO_TAB.anagrafica, 'ST', 'RT', '')
          ANAGRAFICA,
       COD_AMM,
       COD_AOO,
       COD_UO,
       TO_NUMBER (NULL) NI,
       TO_DATE (NULL) DAL,
       TO_DATE (NULL) AL,
       DECODE (COD_UO, NULL, DECODE (COD_AOO, NULL, 'AMM', 'AOO'), 'UO')
          TIPO_INDIRIZZO
  FROM SEG_AMM_AOO_UO_TAB
/
