--liquibase formatted sql
--changeset rdestasio:4.0.1.0_20200622_166.gdo_file_docuemnto_alter failOnError:false
CREATE INDEX FIDO_DOCU_FK ON GDO_FILE_DOCUMENTO
(ID_DOCUMENTO)
/

ALTER TABLE GDO_FILE_DOCUMENTO ADD (
  CONSTRAINT FIDO_DOCU_FK
  FOREIGN KEY (ID_DOCUMENTO)
  REFERENCES GDO_DOCUMENTI (ID_DOCUMENTO)
  ENABLE VALIDATE)
/