--liquibase formatted sql
--changeset esasdelli:AGSPR_TRIGGER_GDO_DOCUMENTI_LOG_TIU runOnChange:true stripComments:false
CREATE OR REPLACE  TRIGGER GDO_DOCUMENTI_LOG_TIU
   BEFORE INSERT OR UPDATE
   ON GDO_DOCUMENTI_LOG
   FOR EACH ROW
BEGIN
   :NEW.DATA_LOG   := TRUNC (:NEW.DATA_UPD);
END GDO_DOCUMENTI_LOG_TIU;
/
