package it.finmatica.protocollo.integrazioni.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-04T10:22:13.619+01:00
 * Generated source version: 3.3.5
 *
 */
@WebServiceClient(name = "DOCAREAProto",
                  wsdlLocation = "file:/Volumes/Lavoro/workarea/clienti/finmatica/protocollo/Protocollo/src/java/it/finmatica/protocollo/integrazioni/ws/DOCAREAProtoSoap1.wsdl",
                  targetNamespace = "http://tempuri.org/")
public class DOCAREAProto extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "DOCAREAProto");
    public final static QName DOCAREAProtoSoap = new QName("http://tempuri.org/", "DOCAREAProtoSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/Volumes/Lavoro/workarea/clienti/finmatica/protocollo/Protocollo/src/java/it/finmatica/protocollo/integrazioni/ws/DOCAREAProtoSoap1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DOCAREAProto.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Volumes/Lavoro/workarea/clienti/finmatica/protocollo/Protocollo/src/java/it/finmatica/protocollo/integrazioni/ws/DOCAREAProtoSoap1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DOCAREAProto(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DOCAREAProto(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DOCAREAProto() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DOCAREAProto(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DOCAREAProto(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DOCAREAProto(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns DOCAREAProtoSoap
     */
    @WebEndpoint(name = "DOCAREAProtoSoap")
    public DOCAREAProtoSoapV2 getDOCAREAProtoSoap() {
        return super.getPort(DOCAREAProtoSoap, DOCAREAProtoSoapV2.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DOCAREAProtoSoap
     */
    @WebEndpoint(name = "DOCAREAProtoSoap")
    public DOCAREAProtoSoapV2 getDOCAREAProtoSoap(WebServiceFeature... features) {
        return super.getPort(DOCAREAProtoSoap, DOCAREAProtoSoapV2.class, features);
    }

}
