package it.finmatica.protocollo.integrazioni.ws;

import it.finmatica.protocollo.integrazioni.ws.dati.Allegato;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.5
 * 2020-03-04T10:22:13.524+01:00
 * Generated source version: 3.3.5
 *
 */
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.RPC)
@WebService(targetNamespace = "http://tempuri.org/", name = "DOCAREAProtoSoapV2")
@XmlSeeAlso({ObjectFactory.class})
public interface DOCAREAProtoSoapV2 {

    @WebMethod
    @RequestWrapper(localName = "inserimento", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.Inserimento")
    @ResponseWrapper(localName = "inserimentoResponse", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.InserimentoResponse")
    @WebResult(name = "InserimentoResult", targetNamespace = "")
    public it.finmatica.protocollo.integrazioni.ws.InserimentoRet inserimento(

        @WebParam(name = "strUserName", targetNamespace = "")
        java.lang.String strUserName,
        @WebParam(name = "strDST", targetNamespace = "")
        java.lang.String strDST
    );

    @WebMethod
    @RequestWrapper(localName = "protocollazione", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.Protocollazione")
    @ResponseWrapper(localName = "protocollazioneResponse", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.ProtocollazioneResponse")
    @WebResult(name = "ProtocollazioneResult", targetNamespace = "")
    public it.finmatica.protocollo.integrazioni.ws.ProtocollazioneRet protocollazione(

        @WebParam(name = "strUserName", targetNamespace = "")
        java.lang.String strUserName,
        @WebParam(name = "strDST", targetNamespace = "")
        java.lang.String strDST
    );

    @WebMethod
    @RequestWrapper(localName = "sostituisciDocumentoPrincipale", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.SostituisciDocumentoPrincipale")
    @ResponseWrapper(localName = "sostituisciDocumentoPrincipaleResponse", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.SostituisciDocumentoPrincipaleResponse")
    @WebResult(name = "sostituisciDocumentoPrincipaleResult", targetNamespace = "")
    public it.finmatica.protocollo.integrazioni.ws.SostituisciDocumentoPrincipaleRet sostituisciDocumentoPrincipale(

        @WebParam(name = "strUserName", targetNamespace = "")
        java.lang.String strUserName,
        @WebParam(name = "strDST", targetNamespace = "")
        java.lang.String strDST
    );

    @WebMethod
    @RequestWrapper(localName = "aggiungiAllegato", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.AggiungiAllegato")
    @ResponseWrapper(localName = "aggiungiAllegatoResponse", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.AggiungiAllegatoResponse")
    @WebResult(name = "AggiungiAllegatoResult", targetNamespace = "")
    public it.finmatica.protocollo.integrazioni.ws.AggiungiAllegatoRet aggiungiAllegato(

        @WebParam(name = "strUserName", targetNamespace = "")
        java.lang.String strUserName,
        @WebParam(name = "strDST", targetNamespace = "")
        java.lang.String strDST
    );

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.LoginResponse")
    @WebResult(name = "LoginResult", targetNamespace = "")
    public it.finmatica.protocollo.integrazioni.ws.LoginRet login(

        @WebParam(name = "strCodEnte", targetNamespace = "")
        java.lang.String strCodEnte,
        @WebParam(name = "strUserName", targetNamespace = "")
        java.lang.String strUserName,
        @WebParam(name = "strPassword", targetNamespace = "")
        java.lang.String strPassword
    );

    @WebMethod
    @RequestWrapper(localName = "smistamentoAction", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.SmistamentoAction")
    @ResponseWrapper(localName = "smistamentoActionResponse", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.SmistamentoActionResponse")
    @WebResult(name = "SmistamentoActionResult", targetNamespace = "")
    public it.finmatica.protocollo.integrazioni.ws.SmistamentoActionRet smistamentoAction(

        @WebParam(name = "strUserName", targetNamespace = "")
        java.lang.String strUserName,
        @WebParam(name = "strDST", targetNamespace = "")
        java.lang.String strDST
    );

    @WebMethod
    @RequestWrapper(localName = "login", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://tempuri.org/", className = "it.finmatica.protocollo.integrazioni.ws.LoginResponse")
    @WebResult(name = "LoginResult", targetNamespace = "")
    public it.finmatica.protocollo.integrazioni.ws.LoginRet loginAoo(

        @WebParam(name = "strCodEnte", targetNamespace = "")
            java.lang.String strCodEnte,
        @WebParam(name = "strAoo", targetNamespace = "")
            java.lang.String strAoo,
        @WebParam(name = "strUserName", targetNamespace = "")
            java.lang.String strUserName,
        @WebParam(name = "strPassword", targetNamespace = "")
            java.lang.String strPassword
    );
}
