--liquibase formatted sql
--changeset mfrancesconi:4.0.0.0_20200226_139_blocchi_upd_mprotocollo

UPDATE BLOCCHI
SET CORPO = REPLACE (CORPO, '_D_DESCRIZIONE_TIPO_REGISTRO', '_T_DESCRIZIONE_TIPO_REGISTRO')
WHERE BLOCCO = 'SEGRETERIAPROTOCOLLO_M_PROTOCOLLO'
 AND AREA = 'SEGRETERIA.PROTOCOLLO'
/