--liquibase formatted sql
--changeset esasdelli:4.0.0.0_20200221_29.ag_privilegi_ruolo_ins failOnError:false
Insert into AG_PRIVILEGI_RUOLO (PRIVILEGIO, RUOLO, AOO)
Values ('MDATAARRBLC', 'AGPSUP', 1)
/

Insert into AG_PRIVILEGI_RUOLO (PRIVILEGIO, RUOLO, AOO)
Values ('MDOCESTBLC', 'AGPSUP', 1)
/

INSERT INTO AG_PRIVILEGI_RUOLO (PRIVILEGIO, RUOLO, AOO)
   SELECT 'IANA', RUOLO, 1
     FROM AG_PRIVILEGI_RUOLO
    WHERE PRIVILEGIO = 'CPROT'
   UNION
   SELECT 'MANA', RUOLO, 1
     FROM AG_PRIVILEGI_RUOLO
    WHERE PRIVILEGIO = 'CPROT'
/

COMMIT
/