
package it.finmatica.affarigenerali.ducd.protocollaSoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED, style = SOAPBinding.Style.RPC)
@WebService(name = "ProtocollaSOAPImpl", targetNamespace = "http://protocolla.ducd.affarigenerali.finmatica.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProtocollaSOAPImpl {


    /**
     * 
     * @param in
     * @return
     *     returns it.finmatica.affarigenerali.ducd.protocolla.ParametriUscita
     */
    @WebMethod
    @WebResult(name = "protocollaReturn", targetNamespace = "http://protocolla.ducd.affarigenerali.finmatica.it")
    @RequestWrapper(localName = "protocolla", targetNamespace = "http://protocolla.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolla.Protocolla")
    @ResponseWrapper(localName = "protocollaResponse", targetNamespace = "http://protocolla.ducd.affarigenerali.finmatica.it", className = "it.finmatica.affarigenerali.ducd.protocolla.ProtocollaResponse")
    public ParametriUscita protocolla(
        @WebParam(name = "in", targetNamespace = "http://protocolla.ducd.affarigenerali.finmatica.it")
            ParametriIngresso in);

}
