
package it.finmatica.affarigenerali.ducd.protocollaSoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ProtocollaSOAPImplService", targetNamespace = "http://protocolla.ducd.affarigenerali.finmatica.it", wsdlLocation = "http://test-agspr-as/ducd/services/ProtocollaSOAPImpl?wsdl")
public class ProtocollaSOAPImplService
    extends Service
{

    private final static URL PROTOCOLLASOAPIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException PROTOCOLLASOAPIMPLSERVICE_EXCEPTION;
    private final static QName PROTOCOLLASOAPIMPLSERVICE_QNAME = new QName("http://protocolla.ducd.affarigenerali.finmatica.it", "ProtocollaSOAPImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://test-agspr-as/ducd/services/ProtocollaSOAPImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PROTOCOLLASOAPIMPLSERVICE_WSDL_LOCATION = url;
        PROTOCOLLASOAPIMPLSERVICE_EXCEPTION = e;
    }

    public ProtocollaSOAPImplService() {
        super(__getWsdlLocation(), PROTOCOLLASOAPIMPLSERVICE_QNAME);
    }

    public ProtocollaSOAPImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PROTOCOLLASOAPIMPLSERVICE_QNAME, features);
    }

    public ProtocollaSOAPImplService(URL wsdlLocation) {
        super(wsdlLocation, PROTOCOLLASOAPIMPLSERVICE_QNAME);
    }

    public ProtocollaSOAPImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PROTOCOLLASOAPIMPLSERVICE_QNAME, features);
    }

    public ProtocollaSOAPImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProtocollaSOAPImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProtocollaSOAPImpl
     */
    @WebEndpoint(name = "ProtocollaSOAPImpl")
    public ProtocollaSOAPImpl getProtocollaSOAPImpl() {
        return super.getPort(new QName("http://protocolla.ducd.affarigenerali.finmatica.it", "ProtocollaSOAPImpl"), ProtocollaSOAPImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProtocollaSOAPImpl
     */
    @WebEndpoint(name = "ProtocollaSOAPImpl")
    public ProtocollaSOAPImpl getProtocollaSOAPImpl(WebServiceFeature... features) {
        return super.getPort(new QName("http://protocolla.ducd.affarigenerali.finmatica.it", "ProtocollaSOAPImpl"), ProtocollaSOAPImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PROTOCOLLASOAPIMPLSERVICE_EXCEPTION!= null) {
            throw PROTOCOLLASOAPIMPLSERVICE_EXCEPTION;
        }
        return PROTOCOLLASOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
