--liquibase formatted sql
--changeset esasdelli:GDM_TRIGGER_AG_SPR_PROTOCOLLI_EMERGENZA_TC runOnChange:true stripComments:false
CREATE OR REPLACE  TRIGGER AG_SPR_PROTOCOLLI_EMERGENZA_TC AFTER INSERT OR UPDATE OR DELETE ON SPR_PROTOCOLLI_EMERGENZA BEGIN INTEGRITYPACKAGE.EXEC_POSTEVENT; END;
/
