--liquibase formatted sql
--changeset esasdelli:20200221_AG_SPR_LETTERE_USCITA_TC runOnChange:true stripComments:false
CREATE OR REPLACE TRIGGER AG_SPR_LETTERE_USCITA_TC AFTER INSERT OR UPDATE OR DELETE ON SPR_LETTERE_USCITA
BEGIN INTEGRITYPACKAGE.EXEC_POSTEVENT; END;
/
