--liquibase formatted sql
--changeset esasdelli:GDM_TRIGGER_AG_SPR_REGISTRO_GIORNALIERO_TC runOnChange:true stripComments:false
CREATE OR REPLACE  TRIGGER AG_SPR_REGISTRO_GIORNALIERO_TC AFTER INSERT OR UPDATE OR DELETE ON SPR_REGISTRO_GIORNALIERO BEGIN INTEGRITYPACKAGE.EXEC_POSTEVENT; END;
/
