--liquibase formatted sql
--changeset esasdelli:GDM_TRIGGER_AG_SPR_PROTOCOLLI_TC runOnChange:true stripComments:false
CREATE OR REPLACE  TRIGGER AG_SPR_PROTOCOLLI_TC AFTER INSERT OR UPDATE OR DELETE ON SPR_PROTOCOLLI BEGIN INTEGRITYPACKAGE.EXEC_POSTEVENT; END;
/
